language: java
jdk:
- openjdk8

branches:
  only:
  - master

env:
  global:
  - secure: COVERALLS_REPO_TOKEN=MJn4UbOPI8YRxvUnG4hZidtPxStWsahEL

# Travis CI 서버의 Cache 활성화
cache:
  directories:
  - '$HOME/.m2/repository'
  - '$HOME/.gradle'

# clean 후 Build (Build시 자동으로 test 수행)
script: "./gradlew clean build"

after_success:
- ./gradlew jacocoTestReport coveralls