server:
  port: 9090

# 로깅
logging:
  level:
    root: info
    org.springframework.boot.web: debug

spring:
  # jconsole admin
  application:
    admin:
      enabled: true
  # Live Reload
  devtools:
    livereload:
      enabled: true
  # datasource
  datasource:
    url: jdbc:h2:mem:testdb
  # h2 console
  h2:
    console:
      enabled: true


property:
  test:
    name: property depth test
propertyTest: test
propertyTestList: a,b,c


fruit:
  list:
    - name: banana
      color: yellow
    - name: apple
      color: red
    - name: water melon
      color: green