server:
  port: 9091

# 로깅
logging:
  level:
    root: info
    org.springframework.boot.web: debug
    org.apache.http: debug

spring:
  # jconsole admin
  application:
    admin:
      enabled: true
  # Live Reload
  devtools:
    livereload:
      enabled: true
  security:
    oauth2:
      client:
        registration:
          facebook:
            client-id: 2519806724913652
            client-secret: 943787cb86a73813d46c7f7a6a8ca792
          google:
            client-id: 699135992487-jqptvth4qddl6cu6mk0240pp95vun4v6.apps.googleusercontent.com
            client-secret: 20UD_HTOZs4Qu5eRQd2AguKt

custom:
  oauth2:
    kakao:
      client-id: ee496cdbb5fd7909d0b309ec6be6abc2